export const NETWORKS = [
  { id:'instagram',    name:'Instagram',      icon:'ti-brand-instagram',   color:'#E1306C', cat:'Social' },
  { id:'tiktok',       name:'TikTok',         icon:'ti-brand-tiktok',      color:'#010101', cat:'Social' },
  { id:'youtube',      name:'YouTube',        icon:'ti-brand-youtube',     color:'#FF0000', cat:'Video' },
  { id:'twitter',      name:'X / Twitter',    icon:'ti-brand-x',           color:'#1DA1F2', cat:'Social' },
  { id:'facebook',     name:'Facebook',       icon:'ti-brand-facebook',    color:'#1877F2', cat:'Social' },
  { id:'threads',      name:'Threads',        icon:'ti-brand-threads',     color:'#101010', cat:'Social' },
  { id:'linkedin',     name:'LinkedIn',       icon:'ti-brand-linkedin',    color:'#0A66C2', cat:'Profesional' },
  { id:'github',       name:'GitHub',         icon:'ti-brand-github',      color:'#181717', cat:'Profesional' },
  { id:'behance',      name:'Behance',        icon:'ti-brand-behance',     color:'#1769FF', cat:'Profesional' },
  { id:'dribbble',     name:'Dribbble',       icon:'ti-brand-dribbble',    color:'#EA4C89', cat:'Profesional' },
  { id:'medium',       name:'Medium',         icon:'ti-brand-medium',      color:'#12100E', cat:'Profesional' },
  { id:'substack',     name:'Substack',       icon:'ti-brand-substack',    color:'#FF6719', cat:'Profesional' },
  { id:'producthunt',  name:'Product Hunt',   icon:'ti-brand-producthunt', color:'#DA552F', cat:'Profesional' },
  { id:'spotify',      name:'Spotify',        icon:'ti-brand-spotify',     color:'#1DB954', cat:'Música' },
  { id:'soundcloud',   name:'SoundCloud',     icon:'ti-brand-soundcloud',  color:'#FF3300', cat:'Música' },
  { id:'bandcamp',     name:'Bandcamp',       icon:'ti-brand-bandcamp',    color:'#1DA0C3', cat:'Música' },
  { id:'applemusic',   name:'Apple Music',    icon:'ti-brand-apple',       color:'#FC3C44', cat:'Música' },
  { id:'twitch',       name:'Twitch',         icon:'ti-brand-twitch',      color:'#9146FF', cat:'Video' },
  { id:'vimeo',        name:'Vimeo',          icon:'ti-brand-vimeo',       color:'#1AB7EA', cat:'Video' },
  { id:'kick',         name:'Kick',           icon:'ti-device-tv',         color:'#53FC18', cat:'Video' },
  { id:'pinterest',    name:'Pinterest',      icon:'ti-brand-pinterest',   color:'#E60023', cat:'Social' },
  { id:'snapchat',     name:'Snapchat',       icon:'ti-brand-snapchat',    color:'#FFFC00', cat:'Social' },
  { id:'reddit',       name:'Reddit',         icon:'ti-brand-reddit',      color:'#FF4500', cat:'Social' },
  { id:'tumblr',       name:'Tumblr',         icon:'ti-brand-tumblr',      color:'#35465C', cat:'Social' },
  { id:'discord',      name:'Discord',        icon:'ti-brand-discord',     color:'#5865F2', cat:'Comunidad' },
  { id:'whatsapp',     name:'WhatsApp',       icon:'ti-brand-whatsapp',    color:'#25D366', cat:'Mensajería' },
  { id:'telegram',     name:'Telegram',       icon:'ti-brand-telegram',    color:'#26A5E4', cat:'Mensajería' },
  { id:'signal',       name:'Signal',         icon:'ti-brand-signal',      color:'#3A76F0', cat:'Mensajería' },
  { id:'wechat',       name:'WeChat',         icon:'ti-brand-wechat',      color:'#07C160', cat:'Mensajería' },
  { id:'line',         name:'Line',           icon:'ti-message-circle',    color:'#06C755', cat:'Mensajería' },
  { id:'paypal',       name:'PayPal',         icon:'ti-brand-paypal',      color:'#003087', cat:'Monetizar' },
  { id:'patreon',      name:'Patreon',        icon:'ti-brand-patreon',     color:'#FF424D', cat:'Monetizar' },
  { id:'kofi',         name:'Ko-fi',          icon:'ti-coffee',            color:'#FF5E5B', cat:'Monetizar' },
  { id:'buymeacoffee', name:'Buy Me a Coffee',icon:'ti-brand-coffee',      color:'#FFDD00', cat:'Monetizar' },
  { id:'gumroad',      name:'Gumroad',        icon:'ti-shopping-bag',      color:'#FF90E8', cat:'Monetizar' },
  { id:'etsy',         name:'Etsy',           icon:'ti-brand-etsy',        color:'#F16521', cat:'Monetizar' },
  { id:'amazon',       name:'Amazon',         icon:'ti-brand-amazon',      color:'#FF9900', cat:'Monetizar' },
  { id:'fiverr',       name:'Fiverr',         icon:'ti-brand-fiverr',      color:'#1DBF73', cat:'Monetizar' },
  { id:'steam',        name:'Steam',          icon:'ti-brand-steam',       color:'#1B2838', cat:'Gaming' },
  { id:'xbox',         name:'Xbox',           icon:'ti-brand-xbox',        color:'#107C10', cat:'Gaming' },
  { id:'playstation',  name:'PlayStation',    icon:'ti-brand-playstation', color:'#003087', cat:'Gaming' },
  { id:'epicgames',    name:'Epic Games',     icon:'ti-device-gamepad',    color:'#2D2D2D', cat:'Gaming' },
  { id:'email',        name:'Email',          icon:'ti-mail',              color:'#EA4335', cat:'Contacto' },
  { id:'phone',        name:'Teléfono',       icon:'ti-phone',             color:'#34A853', cat:'Contacto' },
  { id:'website',      name:'Sitio web',      icon:'ti-world',             color:'#6c63ff', cat:'Contacto' },
  { id:'maps',         name:'Ubicación',      icon:'ti-map-pin',           color:'#FF6B6B', cat:'Contacto' },
]

export const CATEGORIES = ['Todos', ...new Set(NETWORKS.map(n => n.cat))]

// Para temas light y gradient
export const PALETTES_LIGHT = [
  { name:'Púrpura',   accent:'#6c63ff', bg:'#f4f3ff', card:'#ffffff', textColor:'#1a1a2e', muted:'#888888' },
  { name:'Rosa',      accent:'#e91e8c', bg:'#fff0f8', card:'#ffffff', textColor:'#2d0d1f', muted:'#999999' },
  { name:'Verde',     accent:'#00b894', bg:'#f0faf7', card:'#ffffff', textColor:'#0a2922', muted:'#7a9e97' },
  { name:'Azul',      accent:'#0984e3', bg:'#f0f6ff', card:'#ffffff', textColor:'#0a1e40', muted:'#7a9ec4' },
  { name:'Naranja',   accent:'#e17055', bg:'#fff7f4', card:'#ffffff', textColor:'#2e1009', muted:'#a88078' },
  { name:'Pizarra',   accent:'#475569', bg:'#f8fafc', card:'#ffffff', textColor:'#0f172a', muted:'#94a3b8' },
  { name:'Lavanda',   accent:'#8b5cf6', bg:'#faf5ff', card:'#ffffff', textColor:'#1e0a3c', muted:'#a78bfa' },
  { name:'Melocotón', accent:'#f43f5e', bg:'#fff1f2', card:'#ffffff', textColor:'#3b0019', muted:'#fb7185' },
  { name:'Menta',     accent:'#059669', bg:'#ecfdf5', card:'#ffffff', textColor:'#022c22', muted:'#6ee7b7' },
  { name:'Arena',     accent:'#b45309', bg:'#fffbeb', card:'#ffffff', textColor:'#1c1005', muted:'#d97706' },
  { name:'Hielo',     accent:'#0891b2', bg:'#ecfeff', card:'#ffffff', textColor:'#083344', muted:'#67e8f9' },
  { name:'Marfil',    accent:'#9333ea', bg:'#fdfbf7', card:'#fffef5', textColor:'#1a0a00', muted:'#a89a8a' },
  { name:'Candy',     accent:'#ff6fd8', bg:'#fff0fb', card:'#ffe8f9', textColor:'#3a0030', muted:'#d580c0' },
  { name:'Tropical',  accent:'#ff6b35', bg:'#fffbf0', card:'#fff5e0', textColor:'#2d1500', muted:'#ff9a5c' },
  { name:'Bubblegum', accent:'#ff4d9e', bg:'#fff0f9', card:'#ffe8f5', textColor:'#1a0011', muted:'#ff80c0' },
  { name:'Cielo',     accent:'#06b6d4', bg:'#e0f9ff', card:'#ffffff', textColor:'#083344', muted:'#7dd3fc' },
]

// Para dark mode
export const PALETTES_DARK = [
  { name:'Violeta',   accent:'#a78bfa', bg:'#111111', card:'#1e1e1e', textColor:'#eeeeee', muted:'#aaaaaa' },
  { name:'Teal',      accent:'#00cec9', bg:'#0d2137', card:'#162033', textColor:'#e0f0f5', muted:'#7aabba' },
  { name:'Dorado',    accent:'#f0c040', bg:'#1a1500', card:'#241e00', textColor:'#ffe98a', muted:'#b8a860' },
  { name:'Noche',     accent:'#38bdf8', bg:'#0a0f1e', card:'#111827', textColor:'#e2e8f0', muted:'#64748b' },
  { name:'Bosque',    accent:'#86efac', bg:'#052e16', card:'#14532d', textColor:'#dcfce7', muted:'#4ade80' },
  { name:'Vino',      accent:'#fca5a5', bg:'#1c0a0a', card:'#2d1111', textColor:'#fee2e2', muted:'#f87171' },
  { name:'Neón',      accent:'#39ff14', bg:'#0a0a0a', card:'#141414', textColor:'#f0fff0', muted:'#22cc11' },
  { name:'Cobre',     accent:'#fb923c', bg:'#0f0800', card:'#1c1100', textColor:'#fde8c8', muted:'#c2673a' },
  { name:'Marino',    accent:'#818cf8', bg:'#0f0f23', card:'#1a1a35', textColor:'#e0e7ff', muted:'#6366f1' },
  { name:'Carbón',    accent:'#e2e8f0', bg:'#0a0a0a', card:'#181818', textColor:'#f8fafc', muted:'#94a3b8' },
]

// Alias para compatibilidad
export const PALETTES = PALETTES_LIGHT
